# Generated by Django 4.1.7 on 2023-03-15 18:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_app"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="App",
            new_name="Survey",
        ),
    ]
