# Generated by Django 4.1.7 on 2023-03-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_rename_app_survey"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="feedback",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
