# Generated by Django 4.1.7 on 2023-03-16 18:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_feedback"),
        ("projects", "0004_survey_feedback"),
    ]

    operations = []
