# Generated by Django 4.1.7 on 2023-03-16 18:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_merge_0002_feedback_0004_survey_feedback"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Survey",
        ),
    ]
