# Generated by Django 4.1.7 on 2023-03-16 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
        ("notes", "0002_remove_note_notes_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="task",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="tasks.task",
            ),
        ),
    ]
