# Generated by Django 4.1.7 on 2023-03-16 15:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0003_note_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="task",
        ),
    ]
